services:
  app:
    build: .
    container_name: payment-service
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn payment.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=payment_db
      - DJANGO_DB_USER=payment_user
      - DJANGO_DB_PASSWORD=othersecretpassword
    ports:
      - "8007:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: postgres-payment-service
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: othersecretpassword
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-payment-data:
