# Generated by Django 6.0.4 on 2026-05-10 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(help_text='ID wizyty z Appointment-Service', unique=True)),
                ('patient_id', models.UUIDField(help_text='ID pacjenta z Identity-Service')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota w PLN', max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekujące'), ('RESERVED', 'Zarezerwowane'), ('COMPLETED', 'Ukończone'), ('CANCELED', 'Anulowane'), ('EXPIRED', 'Wygasłe')], default='PENDING', max_length=20)),
                ('description', models.CharField(help_text='Opis zamówienia dla PayU', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Czas wygaśnięcia rezerwacji')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment_id'], name='orders_appoint_a3f009_idx'), models.Index(fields=['patient_id'], name='orders_patient_702b63_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payu_order_id', models.CharField(help_text='ID zamówienia w PayU', max_length=100, unique=True)),
                ('payu_status', models.CharField(choices=[('PENDING', 'Oczekująca'), ('COMPLETED', 'Ukończona'), ('FAILED', 'Nie powiodła się'), ('CANCELED', 'Anulowana'), ('REFUNDED', 'Zwrócona')], default='PENDING', help_text='Status z API PayU', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('payu_response', models.JSONField(blank=True, help_text='Pełna odpowiedź z PayU', null=True)),
                ('payu_notify_response', models.JSONField(blank=True, help_text='Dane z webhooka IPN', null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Czas potwierdzenia płatności', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ORDER_CREATED', 'Zamówienie utworzone'), ('ORDER_EXPIRED', 'Zamówienie wygasłe'), ('PAYMENT_INITIATED', 'Płatność zainicjowana'), ('PAYMENT_COMPLETED', 'Płatność ukończona'), ('PAYMENT_FAILED', 'Płatność nie powiodła się'), ('PAYMENT_REFUND_INITIATED', 'Zwrot zainicjowany'), ('PAYMENT_REFUND_COMPLETED', 'Zwrot ukończony'), ('WEBHOOK_RECEIVED', 'Webhook odebrany'), ('WEBHOOK_PROCESSED', 'Webhook przetworzony')], max_length=50)),
                ('actor_id', models.UUIDField(blank=True, help_text='Użytkownik/system który wykonał akcję', null=True)),
                ('actor_type', models.CharField(choices=[('USER', 'Użytkownik'), ('SYSTEM', 'System'), ('WEBHOOK', 'Webhook')], default='SYSTEM', max_length=20)),
                ('details', models.JSONField(help_text='Szczegóły akcji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payment.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payment.payment')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, help_text='Powód zmiany', max_length=255)),
                ('webhook_data', models.JSONField(blank=True, help_text='Dane z webhooka, jeśli zmianę wyzwolił webhook', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payment.payment')),
            ],
            options={
                'db_table': 'payment_statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payu_order_id'], name='payments_payu_or_4cc566_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payu_status'], name='payments_payu_st_7f0070_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_id'], name='audit_logs_actor_i_0badd2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'),
        ),
    ]
